### ISSUE TITLE
Accept requests where `query` is a parsed AST representation

### ISSUE THREAD

**Issue by spawnia** [APIs-guru/graphql-over-http#176]
I have recently come to know that certain GraphQL tooling - apparently `apollo` and `weaver` proxies and gateways - send parsed representations of GraphQL operations instead of strings. Some servers do support this, see https://github.com/webonyx/graphql-php/issues/279 for context.

Can and should we standardize this?

First of all, we would need a canonical specification of the AST format. As far as I can tell, the AST representation of a GraphQL document is not standardized in the GraphQL specification.

Next, I think this feature should most likely be optional - meaning servers can choose to support it, but are not required to do so. Clients must not expect this to work by default - but can it discover if a server supports it?

**Comment by glasser** [comment]
@spawnia Can you clarify where Apollo products do this? The closest thing I can think of is that Apollo Server explicitly [tries to detect whether this has happened in order to reject it with a clear error message](https://github.com/apollographql/apollo-server/blob/482f0d75d4fbfcd3d4e278d6ad9f6dfe42105f31/packages/apollo-server-core/src/runHttpQuery.ts#L498-L507). If other Apollo products do this, I suspect that's a bug.

**Comment by glasser** [comment]
I see that the issue you have linked says basically what you said, four years ago. I would be pretty surprised to learn that this is accurate today.

**Comment by spawnia** [comment]
This issue was completely based on hearsay. Closing until I hear of a concrete case where this is actually used. Thanks for the feedback.
